notifications:
  email:
    recipients:
      - rich@flatcap.org
    on_success: change
    on_failure: always

sudo: false
dist: trusty

language: c
compiler: gcc
cache: ccache

addons:
  apt:
    packages:
      - autopoint
      - docbook-simple
      - docbook-xsl
      - gettext
      - libdb-dev
      - libgdbm-dev
      - libgnutls-dev
      - libgpgme11-dev
      - libgss-dev
      - libkyotocabinet-dev
      - liblmdb-dev
      - liblua5.2-dev
      - libnotmuch-dev
      - libqdbm-dev
      - libsasl2-dev
      - libslang2-dev
      - libssl-dev
      - libtokyocabinet-dev
      - libxml2-utils
      - lua5.2
      - lynx
      - xsltproc
      - libidn2-0-dev

git:
  depth: 3

# install:
#   - git clone --depth 1 https://github.com/neomutt/travis-build.git ~/config

before_script:
  - ccache --zero-stats

script:
  - ./configure --disable-idn --idn2
  - make
  # - ~/config/build

after_script:
  - ccache --show-stats

